name: Test pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      SELAMLAR: HELLO
    steps:
      - name: Checkout adimi
        uses: actions/checkout@v2

      - name: Bekir env Tanimlama
        run: |
          echo "Hello World"
          echo $Bekir
        env:
          Bekir: "Bu bekir env düzenlendi."
      - name: Bu da ikinci adim
        run: |
          echo $DAY_OF_WEEK
          echo $SELAMLAR
          echo $Bekir
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Bu ikinci Job
        run: |
          echo "This is the second job"
          echo $DAY_OF_WEEK
          echo $SELAMLAR
          echo $Bekir
