name: Test pipeline

on:
  push:
    branches:
    - master
  workflow_dispath:

jobs:
  runs-on: ubuntu-la test

  steps:
  - name: Checkout-adimi
  - uses: actions/check-out@v4
  - name: Enviroment variable listeleme
  - run: printev 
