name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday # Workflow seviyesinde genel ortam değişkeni tanımlama

jobs:
  test-job:
    runs-on: ubuntu-latest # Job'un çalışacağı ortam

    env: # Job seviyesinde ortam değişkeni tanımlama
      SELAMLAR: HELLO

    steps: # Adımlar
      - name: Checkout repository
        uses: actions/checkout@v2 # GitHub reposunu checkout etme

      - name: Generate log file
        run: |
          echo "This is a test log" >> logs.txt
          echo "Log entry 1" >> logs.txt
          echo "Log entry 2" >> logs.txt
          echo "Log entry 3" >> logs.txt
          echo "Log entry 4" >> logs.txt

      - name: Upload logs as artifact # Log dosyasını artifact olarak yükleme
        uses: actions/upload-artifact@v4
        with:
          name: logs # Artifact adı
          path: logs.txt # Artifact olarak yüklenecek dosyanın yolu

  test-job-2:
    runs-on: ubuntu-latest
    needs: test-job # test-job'un başarılı olmasını bekler

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download logs artifact # Artifact'ı indirme
        uses: actions/download-artifact@v4
        with:
          name: logs # Artifact adı
          path: ./downloaded_logs # Artifact dosyasını kaydedeceğimiz dizin

      - name: Display the logs # İndirilen log dosyasını görüntüleme
        run: |
          cat ./downloaded_logs/logs.txt  # Artifact dosyasının içeriğini görüntüle

      - name: Print some environment variables
        run: |
          echo $DAY_OF_WEEK  # Workflow seviyesinde tanımlanan DAY_OF_WEEK değişkeni burada geçerli
          echo $SELAMLAR  # Job seviyesinde tanımlanan SELAMLAR değişkeni burada geçerli
