name: Test pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  test-job:  
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Bekir env Tanimlama
        run: |
          echo "Hello World"
          echo $Bekir
        env:
          Bekir: "Bu bekir env"
