name: Test pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test-job:
    runs-on: ubuntu-latest # çalışacağı ortam
    env: # job seviyesinde env tanımlama
      SELAMLAR: HELLO
    steps: # adımlar
      - name: Checkout adimi # adim ismi
        uses: actions/checkout@v2 # action kullanımı

      - name: Bekir env Tanimlama # step seviyesinde env tanımlama
        run: |
          echo "Hello World"
          echo $Bekir
        env: # step seviyesinde env tanımlama
          Bekir: "Bu bekir env düzenlendi."
      - name: Bu da ikinci adim
        run: |
          echo $DAY_OF_WEEK 
          echo $SELAMLAR
          echo $Bekir
  test-job-2:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Bu ikinci Job
        run: |
          echo "This is the second job"
          echo $DAY_OF_WEEK
          echo $SELAMLAR
          echo $Bekir
